//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class bill
    {
        [Display(Name = "Bill#")]
        public int bill_id { get; set; }
        [Display(Name = "Bill Date")]
        public Nullable<System.DateTime> bill_date { get; set; }
        public string Payment { get; set; }
        public Nullable<int> Amount { get; set; }
        [Display(Name = "Purchase Order")]
        public Nullable<int> po_id { get; set; }
        [Display(Name = "PO#")]
        public virtual purchase_order purchase_order { get; set; }
    }
}
