//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class purchase_order_line
    {
        [Display(Name = "Chalan#")]
        public int pol_id { get; set; }
        [Display(Name = "PO#")]
        public int Line_No { get; set; }
        [Display(Name = "Quality of Paper")]
        public string Paper_quality { get; set; }
        [Display(Name = "Quantity")]
        public Nullable<int> Quantity { get; set; }
        [Display(Name = "Number of Plys")]
        public string Number_of_ply { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> length { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> Amount { get; set; }
        [Display(Name = "PO#")]
        public Nullable<int> po_id { get; set; }
        [Display(Name = "PO#")]
        public virtual purchase_order purchase_order { get; set; }
    }
}
